[package]
name = "RustGame"
version = "0.1.0"
edition = "2021"
authors = ["nicolas.reboule@epitech.eu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emerald = "0.2.63"
